# Generated by Django 5.0.2 on 2024-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_books_genre_books_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(default='media/book.png', upload_to='media'),
        ),
    ]
