# Generated by Django 5.0.2 on 2024-02-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreview_book_bookreview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_author',
            new_name='author',
        ),
    ]
